use SmartOneCfg
go

ALTER DATABASE smartonecfg SET RECOVERY SIMPLE WITH NO_WAIT

--简单模式
ALTER DATABASE smartonecfg SET RECOVERY SIMPLE


DBCC SHRINKFILE (N'TMPLOG_SmartOneCfg' , 11, TRUNCATEONLY) 


ALTER DATABASE smartonecfg SET RECOVERY FULL WITH NO_WAIT

--还原为完全模式
ALTER DATABASE smartonecfg SET RECOVERY FULL 