
package org.opcfoundation.webservices.xmlda._1_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-20T16:07:36.575+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class OPCXMLDAWrapperServiceSoap_OPCXMLDAWrapperServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://opcfoundation.org/webservices/XMLDA/1.0/", "OPC_XML_DA_WrapperService");

    private OPCXMLDAWrapperServiceSoap_OPCXMLDAWrapperServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OPCXMLDAWrapperService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OPCXMLDAWrapperService ss = new OPCXMLDAWrapperService(wsdlURL, SERVICE_NAME);
        OPCXMLDAWrapperServiceSoap port = ss.getOPCXMLDAWrapperServiceSoap();  
        
        {
        System.out.println("Invoking read...");
        org.opcfoundation.webservices.xmlda._1.RequestOptions _read_options = null;
        org.opcfoundation.webservices.xmlda._1.ReadRequestItemList _read_itemList = null;
        javax.xml.ws.Holder<org.opcfoundation.webservices.xmlda._1.ReplyBase> _read_readResult = new javax.xml.ws.Holder<org.opcfoundation.webservices.xmlda._1.ReplyBase>();
        javax.xml.ws.Holder<org.opcfoundation.webservices.xmlda._1.ReplyItemList> _read_rItemList = new javax.xml.ws.Holder<org.opcfoundation.webservices.xmlda._1.ReplyItemList>();
        javax.xml.ws.Holder<java.util.List<org.opcfoundation.webservices.xmlda._1.OPCError>> _read_errors = new javax.xml.ws.Holder<java.util.List<org.opcfoundation.webservices.xmlda._1.OPCError>>();
        port.read(_read_options, _read_itemList, _read_readResult, _read_rItemList, _read_errors);

        System.out.println("read._read_readResult=" + _read_readResult.value);
        System.out.println("read._read_rItemList=" + _read_rItemList.value);
        System.out.println("read._read_errors=" + _read_errors.value);

        }
        {
        System.out.println("Invoking write...");
        org.opcfoundation.webservices.xmlda._1.Write _write_parameters = null;
        org.opcfoundation.webservices.xmlda._1.WriteResponse _write__return = port.write(_write_parameters);
        System.out.println("write.result=" + _write__return);


        }
        {
        System.out.println("Invoking subscribe...");
        org.opcfoundation.webservices.xmlda._1.Subscribe _subscribe_parameters = null;
        org.opcfoundation.webservices.xmlda._1.SubscribeResponse _subscribe__return = port.subscribe(_subscribe_parameters);
        System.out.println("subscribe.result=" + _subscribe__return);


        }
        {
        System.out.println("Invoking browse...");
        org.opcfoundation.webservices.xmlda._1.Browse _browse_parameters = null;
        org.opcfoundation.webservices.xmlda._1.BrowseResponse _browse__return = port.browse(_browse_parameters);
        System.out.println("browse.result=" + _browse__return);


        }
        {
        System.out.println("Invoking subscriptionCancel...");
        org.opcfoundation.webservices.xmlda._1.SubscriptionCancel _subscriptionCancel_parameters = null;
        org.opcfoundation.webservices.xmlda._1.SubscriptionCancelResponse _subscriptionCancel__return = port.subscriptionCancel(_subscriptionCancel_parameters);
        System.out.println("subscriptionCancel.result=" + _subscriptionCancel__return);


        }
        {
        System.out.println("Invoking subscriptionPolledRefresh...");
        org.opcfoundation.webservices.xmlda._1.SubscriptionPolledRefresh _subscriptionPolledRefresh_parameters = null;
        org.opcfoundation.webservices.xmlda._1.SubscriptionPolledRefreshResponse _subscriptionPolledRefresh__return = port.subscriptionPolledRefresh(_subscriptionPolledRefresh_parameters);
        System.out.println("subscriptionPolledRefresh.result=" + _subscriptionPolledRefresh__return);


        }
        {
        System.out.println("Invoking getStatus...");
        org.opcfoundation.webservices.xmlda._1.GetStatus _getStatus_parameters = null;
        org.opcfoundation.webservices.xmlda._1.GetStatusResponse _getStatus__return = port.getStatus(_getStatus_parameters);
        System.out.println("getStatus.result=" + _getStatus__return);


        }
        {
        System.out.println("Invoking getProperties...");
        org.opcfoundation.webservices.xmlda._1.GetProperties _getProperties_parameters = null;
        org.opcfoundation.webservices.xmlda._1.GetPropertiesResponse _getProperties__return = port.getProperties(_getProperties_parameters);
        System.out.println("getProperties.result=" + _getProperties__return);


        }

        System.exit(0);
    }

}
